name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          npm install -g bun
          bun install
          bun run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: docs/.vitepress/dist

  # deploy-to-server:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifact

  #     - uses: easingthemes/ssh-deploy@main
  #       with:
  #         REMOTE_HOST: ${{ secrets.SERVER_HOST }}
  #         REMOTE_PORT: ${{ secrets.SERVER_PORT }}
  #         REMOTE_USER: ${{ secrets.SERVER_USER }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
  #         SOURCE: "."
  #         ARGS: "-azr --delete"
  #         TARGET: "${{ secrets.SERVER_PATH }}/${{ github.event.repository.name }}/"

  push-to-branch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}

      - run: |
          git checkout --orphan site
          git rm -rf . >/dev/null

      - uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "upload build artifact to site branch"
          git push origin site -f
